library(readxl)
library(readr)
library(stringi)
library(tidyr)

path_DS <- "V:/Onroad/Projects_Inventory/2017_NEI_NC_Onroad_EI"
file_DS <- sprintf("%s/2017_EPA_NEI_Design_Sheet.xlsx",path_DS)

DS <- read_excel(file_DS,sheet = "XMLImporter")
#STY <- read_excel(file_DS,sheet = "sourceTypeYear")
#VMT <- read_excel(file_DS,sheet ="VMT Converter")
#FuelSu<- read_excel(file_DS,sheet ="FuelSupply")
#FuelUs<- read_excel(file_DS,sheet ="FuelUsageFractions")
#FuelFo<- read_excel(file_DS,sheet ="FuelFormulation")
#AVFT  <- read_excel(file_DS,sheet ="AFVT")
#MET <- read_excel(file_DS,sheet = "zoneMonthHour")
#RunSpec <- read_excel(file_DS,sheet = "RunSpec")
#AVGSPD <- read_excel(file_DS,sheet = "avgSpdDistribution")
#STAD <- read_excel(file_DS,sheet = "sourceTypeAgeDistribution")
#MDVF <- read_excel(file_DS,sheet = "monthVMTFraction_dayVMTFraction")
#IMF <- read_excel(file_DS,sheet = "IMCoverage")
DS[is.na(DS)] <- "-"
checkfile <- sprintf("%s/XML_Importers/XML_importer_2017_EPANEI.txt",path_DS)
if (file.exists(checkfile)) file.remove(checkfile)
write("rem",checkfile,append = TRUE)
write("c:",checkfile,append = TRUE)
write("cd \"C:\\Users\\Public\\EPA\\MOVES\\MOVES2014a\"",checkfile,append = TRUE)
write("call setenv.bat",checkfile,append = TRUE)
write("call ant compile",checkfile,append = TRUE)
write("rem -----------------------------------------------------------",checkfile,append = TRUE)
for (c in 1:length(DS$countyID)){
  XMLfile <- sprintf("%s/%s",gsub("\\\\","/",DS$Directory[c]),DS$Filename[c])
  line <- sprintf("    Java -Xmx512M gov.epa.otaq.moves.master.commandline.MOVESCommandLine -i %s",XMLfile)
  write(line,checkfile,append = TRUE)
}
filename_bat <- gsub("txt","bat",checkfile)
file.rename(checkfile,filename_bat)
